2024-06-10 10:35:08,104 - httpx - INFO - HTTP Request: POST https://api.telegram.org/botTOKEN/getMe "HTTP/1.1 404 Not Found"
2024-06-10 10:35:19,667 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getMe "HTTP/1.1 200 OK"
2024-06-10 10:35:19,745 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/deleteWebhook "HTTP/1.1 200 OK"
2024-06-10 10:35:19,746 - telegram.ext.Application - INFO - Application started
2024-06-10 10:35:30,041 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:35:40,102 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:35:50,147 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:35:59,945 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:36:00,486 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 10:36:10,006 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:36:20,047 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:36:30,093 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:36:40,170 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:36:51,362 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:37:01,420 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:37:11,492 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:37:21,554 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:37:31,637 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:37:41,706 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:37:51,754 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:38:01,825 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:38:11,881 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:38:21,932 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:38:32,024 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:38:42,078 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:38:52,124 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:39:02,192 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:39:12,249 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:39:22,308 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:39:32,442 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:39:42,493 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:39:52,573 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:40:02,882 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:40:40,771 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:42:00,864 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:42:10,974 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:42:21,012 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:42:31,163 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:42:41,650 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:42:51,740 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:43:01,852 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:43:11,980 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:43:22,422 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:43:32,685 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:43:42,730 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:43:52,817 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:44:02,873 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:44:12,932 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:44:23,013 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:44:33,065 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:44:43,191 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:44:53,284 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:45:03,393 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:45:13,506 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:45:23,708 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:45:33,872 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:45:43,983 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:45:54,032 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:46:04,286 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:46:14,603 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:46:24,778 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:46:34,842 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:46:44,916 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:46:55,035 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:47:06,369 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:47:16,440 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:47:26,793 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:47:37,003 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:47:47,788 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:47:58,118 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:48:08,285 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:48:18,354 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:48:32,668 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:48:42,736 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:48:52,791 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:49:02,888 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:49:13,087 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:49:23,501 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:49:33,727 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:49:43,802 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:49:53,908 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:50:04,123 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:50:14,279 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:50:24,593 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:50:34,666 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:50:44,906 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:50:55,120 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:51:05,401 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:51:15,514 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:51:25,636 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:51:35,804 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:51:45,967 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:51:56,102 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:52:06,190 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:52:16,338 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:52:26,553 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:52:36,733 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:52:46,837 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:52:57,032 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:53:07,164 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:53:17,270 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:53:27,435 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:53:37,654 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:53:47,711 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:53:57,825 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:54:07,995 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:54:18,138 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:54:28,228 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:54:38,307 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:54:48,436 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:54:58,529 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:55:08,739 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:55:18,844 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:55:28,968 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:55:39,030 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:55:49,474 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:55:59,616 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:56:09,691 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:56:19,859 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:56:29,914 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:56:40,542 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:56:50,733 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:57:00,820 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:57:10,956 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:57:21,063 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:57:31,161 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:57:41,777 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:57:51,823 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:58:01,945 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:58:12,216 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:58:22,306 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:58:32,770 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:58:42,998 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:58:53,141 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:59:03,706 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:59:13,830 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:59:24,011 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:59:34,290 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:59:44,552 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 10:59:54,695 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:00:04,761 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:00:14,917 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:00:25,275 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:00:35,694 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:00:45,791 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:00:55,924 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:01:05,991 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:01:16,241 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:01:26,351 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:01:36,607 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:01:46,749 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:01:56,890 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:02:07,007 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:02:17,327 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:02:27,482 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:02:37,637 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:02:47,750 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:02:57,813 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:03:07,931 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:03:18,071 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:03:28,311 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:03:38,569 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:03:48,716 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:03:58,811 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:04:08,885 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:04:18,963 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:04:29,055 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:04:39,105 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:04:49,240 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:04:59,488 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:05:09,672 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:05:19,749 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:05:29,916 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:05:40,066 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:05:50,294 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:06:00,341 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:06:10,398 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:06:20,442 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:06:30,502 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:06:40,579 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:06:50,616 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:07:00,670 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:07:10,720 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:07:20,865 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:07:31,028 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:07:41,125 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:07:51,270 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:08:01,310 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:08:11,376 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:08:21,443 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:08:31,486 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:08:41,551 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:08:51,664 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:09:01,695 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:09:11,759 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:09:21,808 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:09:31,900 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:09:41,952 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:09:51,998 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:10:02,035 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:10:12,068 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:10:22,126 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:10:32,215 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:10:42,285 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:10:52,339 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:11:02,373 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:11:12,462 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:11:22,522 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:11:32,645 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:11:42,699 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:11:52,738 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:12:02,774 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:12:12,817 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:12:22,855 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:12:32,889 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:12:42,928 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:12:52,976 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:13:03,043 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:13:13,117 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:13:23,147 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:13:33,184 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:13:43,228 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:13:53,275 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:14:03,302 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:14:13,332 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:14:23,371 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:14:33,402 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:14:43,437 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:14:53,487 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:15:03,781 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:15:13,835 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:15:23,879 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:15:34,181 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:15:44,218 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:15:54,623 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:16:04,909 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:16:15,006 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:16:25,165 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:16:35,211 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:16:45,246 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:16:55,680 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:17:05,735 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:17:15,789 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:17:25,828 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:17:36,000 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:17:46,041 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:17:56,097 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:18:06,172 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:18:16,239 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:18:26,277 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:18:36,320 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:18:46,377 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:18:56,431 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:19:06,678 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:19:16,714 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:19:26,806 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:19:36,872 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:19:46,909 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:19:56,951 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:20:06,992 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:20:17,027 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:20:27,071 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:20:37,949 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:20:48,110 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:20:58,240 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:21:08,367 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:21:20,929 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:21:31,018 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:21:41,606 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:22:01,639 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: All connection attempts failed
2024-06-10 11:22:01,640 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed
2024-06-10 11:22:02,652 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: All connection attempts failed
2024-06-10 11:22:02,652 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed
2024-06-10 11:22:04,157 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: All connection attempts failed
2024-06-10 11:22:04,158 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed
2024-06-10 11:22:11,276 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 409 Conflict"
2024-06-10 11:22:11,277 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-06-10 11:22:11,277 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 383, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-06-10 11:22:24,780 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:22:34,918 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:22:51,534 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno -3] Temporary failure in name resolution
2024-06-10 11:22:51,535 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno -3] Temporary failure in name resolution
2024-06-10 11:22:52,545 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: All connection attempts failed
2024-06-10 11:22:52,545 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed
2024-06-10 11:22:54,055 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: All connection attempts failed
2024-06-10 11:22:54,055 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed
2024-06-10 11:22:57,960 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno -2] Name or service not known
2024-06-10 11:22:57,960 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno -2] Name or service not known
2024-06-10 11:23:04,102 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno -2] Name or service not known
2024-06-10 11:23:04,103 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno -2] Name or service not known
2024-06-10 11:23:09,912 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno -3] Temporary failure in name resolution
2024-06-10 11:23:09,912 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno -3] Temporary failure in name resolution
2024-06-10 11:23:17,518 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno -3] Temporary failure in name resolution
2024-06-10 11:23:17,518 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno -3] Temporary failure in name resolution
2024-06-10 11:23:28,924 - telegram.ext.Updater - ERROR - Error while getting Updates: httpx.ConnectError: [Errno -3] Temporary failure in name resolution
2024-06-10 11:23:28,925 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 389, in polling_action_cb
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 300, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: [Errno -3] Temporary failure in name resolution
2024-06-10 11:23:56,209 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:24:06,355 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:24:16,484 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:24:26,630 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:24:36,760 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:24:46,905 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:24:57,043 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:25:07,171 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:25:17,213 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:25:27,252 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:25:37,381 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:25:47,527 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:25:57,656 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:26:07,774 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:26:17,932 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:26:28,082 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:26:38,320 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:26:48,553 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:26:56,476 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:27:06,580 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:27:16,710 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:27:26,857 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:27:36,915 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:27:46,981 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:27:57,030 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:28:07,090 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:28:17,238 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:28:27,293 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:28:37,370 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:28:47,445 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:28:57,583 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:29:07,713 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:29:17,753 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:29:27,894 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:29:37,953 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:29:48,059 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:29:58,205 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:30:08,334 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:30:18,381 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:30:28,422 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:30:38,508 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:30:48,681 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:30:58,826 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:31:08,956 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:31:18,996 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:31:29,040 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:31:39,096 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:31:49,141 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:31:59,243 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:32:09,280 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:32:19,408 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:32:29,449 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:32:39,486 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:32:49,624 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:32:59,754 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:33:09,795 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:33:19,935 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:33:29,974 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:33:40,017 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:33:50,077 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:34:00,281 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:34:10,616 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:34:20,663 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:34:30,705 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:34:40,750 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:34:50,811 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:35:00,902 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:35:11,033 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:35:21,179 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:35:31,250 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:35:41,284 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:35:51,329 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:36:01,415 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:36:11,458 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:36:21,596 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:36:31,726 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:36:41,862 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:36:52,012 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:37:02,147 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:37:12,182 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:37:22,314 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:37:32,459 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:37:42,501 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:37:52,576 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:38:02,851 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:38:12,914 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:38:23,012 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:38:31,352 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:38:37,629 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:38:37,869 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 11:38:47,701 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:38:57,767 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:39:07,834 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:39:17,943 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:39:28,119 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:39:38,196 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:39:48,246 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:39:49,641 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:39:50,153 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 11:39:59,766 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:40:09,817 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:40:19,862 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:40:30,302 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:40:40,431 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:40:44,574 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:40:44,850 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 11:40:54,646 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:40:59,214 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:40:59,216 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-06-10 11:40:59,216 - telegram.ext.Application - INFO - Application.stop() complete
2024-06-10 11:41:01,667 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getMe "HTTP/1.1 200 OK"
2024-06-10 11:41:01,714 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/deleteWebhook "HTTP/1.1 200 OK"
2024-06-10 11:41:01,717 - telegram.ext.Application - INFO - Application started
2024-06-10 11:41:05,125 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:41:05,215 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 11:41:08,299 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:41:18,359 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:41:28,400 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:41:38,442 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:41:48,509 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:41:58,569 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:42:08,667 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:42:18,766 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:42:28,874 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:42:38,957 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:42:49,238 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:42:59,309 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:43:09,367 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:43:19,513 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:43:29,579 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:43:39,651 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:43:49,690 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:43:59,760 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:44:09,844 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:44:19,902 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:44:30,004 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:44:40,129 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:44:50,193 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:45:00,242 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:45:10,304 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:45:20,408 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:45:30,546 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:45:40,619 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:45:50,696 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:46:00,782 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:46:10,864 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:46:20,906 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:46:30,967 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:46:41,004 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:46:51,110 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:47:01,171 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:47:11,405 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:47:21,440 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:47:31,499 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:47:41,652 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:47:51,767 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:48:01,968 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:48:12,133 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:48:22,188 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:48:32,279 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:48:42,334 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:48:52,416 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:49:02,489 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:49:12,600 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:49:22,720 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:49:32,793 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:49:42,935 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:49:52,999 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:50:03,045 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:50:13,275 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:50:23,343 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:50:33,587 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:50:43,761 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:50:53,845 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:51:03,891 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:51:13,951 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:51:24,055 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:51:34,106 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:51:44,232 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:51:54,262 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:52:04,311 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:52:14,401 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:52:24,454 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:52:34,485 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:52:44,526 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:52:54,567 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:53:04,900 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:53:14,952 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:53:25,004 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:53:35,103 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:53:45,364 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:53:55,414 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:54:05,484 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:54:15,526 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:54:25,578 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:54:35,949 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:54:46,797 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:54:57,458 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 11:55:08,020 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:00:16,128 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getMe "HTTP/1.1 200 OK"
2024-06-10 12:00:16,347 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/deleteWebhook "HTTP/1.1 200 OK"
2024-06-10 12:00:16,350 - telegram.ext.Application - INFO - Application started
2024-06-10 12:00:18,383 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:00:18,677 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 12:00:19,465 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 12:00:20,426 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 12:00:21,036 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 12:00:50,693 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:01:01,409 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:01:46,745 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:01:57,315 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:02:07,955 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:02:18,777 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:02:29,850 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:02:40,611 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:02:51,577 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:03:04,246 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:03:17,969 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:04:31,910 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:04:42,287 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:04:52,782 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:05:07,132 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:05:19,511 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:05:33,583 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:08:17,710 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:08:27,970 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:08:39,970 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:10:12,083 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:10:24,589 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:10:35,960 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:10:49,987 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:11:17,820 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:11:28,487 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:11:42,076 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:13:36,241 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:13:46,390 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:13:56,873 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:14:39,964 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:14:50,067 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:15:00,570 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:15:10,649 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:15:20,989 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:15:33,399 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:15:47,158 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:16:00,572 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:16:11,160 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:16:20,131 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:16:27,315 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:16:27,911 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 12:16:28,680 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 12:16:37,429 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:16:47,570 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:16:51,507 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:16:51,508 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-06-10 12:16:51,508 - telegram.ext.Application - INFO - Application.stop() complete
2024-06-10 12:16:54,895 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getMe "HTTP/1.1 200 OK"
2024-06-10 12:16:55,295 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/deleteWebhook "HTTP/1.1 200 OK"
2024-06-10 12:16:55,298 - telegram.ext.Application - INFO - Application started
2024-06-10 12:17:01,857 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:17:02,439 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/sendMessage "HTTP/1.1 200 OK"
2024-06-10 12:17:05,171 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:17:07,215 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:17:07,950 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:17:18,034 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:17:31,110 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot7494756685:AAF439qaWwEluY7m68b1xyK718LowbZCtaU/getUpdates "HTTP/1.1 200 OK"
2024-06-10 12:17:44,639 - telegram.ext.Updater - ERROR - Error while calling `get_updates` one more time to mark all fetched updates as read: %s. Suppressing error to ensure graceful shutdown. When polling for updates is restarted, updates may be fetched again. Please adjust timeouts via `ApplicationBuilder` or the parameter `get_updates_request` of `Bot`.
Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_updater.py", line 439, in _get_updates_cleanup
    await self.bot.get_updates(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 645, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 4230, in get_updates
    await self._post(
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 618, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 353, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/_bot.py", line 647, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 342, in _request_wrapper
    raise exc
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 332, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igor/.local/share/virtualenvs/python_bot-_MTLMany/lib/python3.12/site-packages/telegram/request/_httpxrequest.py", line 293, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
2024-06-10 12:17:44,651 - telegram.ext.Application - INFO - Application is stopping. This might take a moment.
2024-06-10 12:17:44,651 - telegram.ext.Application - INFO - Application.stop() complete
